build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

real_test:
  stage: test
  image: python:3.9.4
  script:
    - echo "Starting the real test"
    - pip install correctionlib
    - python script/testJSONfiles.py
    - echo "Done"

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'
