test:
  stage: test
  image: python:3.9.4
  script:
    - pip install correctionlib==2.0.0rc4
    - git clone https://sdonato:Wu9CyAMDWsxd25JtdP9A@gitlab.cern.ch/sdonato/jsonpog-integration.git  -b master cms-nanoAOD-repo --depth 1
    - script/runTest.sh
#    - find . -name *.json | xargs correction validate --version 2

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'
